apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
type: Opaque
stringData:
  mistral-key: "{{ .Values.secrets.llmApiKey }}"
  openai-key: "{{ .Values.secrets.openaiApiKey }}"
  telegram-token: "{{ .Values.secrets.telegramToken }}"
  secret-encryption-key: "{{ .Values.secrets.secretEncryptionKey }}"
  solana-private-key: "{{ .Values.secrets.solanaPrivateKey }}"
  frp-client-token: "{{ .Values.secrets.frpClientToken.value }}"
