apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-frpc-entrypoint-config"
data:
  entrypoint.sh: |
    #!/bin/sh
    # Append the secretKey to the frpc.toml file
    echo "secretKey = \"$FRP_STCP_SECRET_KEY\"" >> /etc/frp/frpc.toml
    # Execute the original frpc command
    exec frpc -c /etc/frp/frpc.toml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-frpc-config"
data:
  frpc.toml: |
    serverAddr = "aura.zae.life"
    serverPort = 7000

    [auth]
    method = "token"

    [auth.tokenSource]
    type = "file"

    [auth.tokenSource.file]
    path = "/etc/frp/token"

    [[proxies]]
    name = "frontend"
    type = "tcp"
    localIP = "{{ .Release.Name }}-frontend"
    localPort = {{ .Values.frontend.service.port }}
    remotePort = 8081

    [[proxies]]
    name = "gateway"
    type = "tcp"
    localIP = "{{ .Release.Name }}-gateway"
    localPort = 8000
    remotePort = 8082

    [[proxies]]
    name = "grafana"
    type = "tcp"
    localIP = {{ .Values.tunnel.grafana.localIP | quote }}
    localPort = {{ .Values.tunnel.grafana.localPort }}
    remotePort = {{ .Values.tunnel.grafana.remotePort }}

    [[proxies]]
    name = "nats-hidden"
    type = "stcp"
    localIP = "{{ .Release.Name }}-nats"
    localPort = 4222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frpc-tunnel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
      - name: frpc
        image: "{{ .Values.tunnel.image.repository }}:{{ .Values.tunnel.image.tag }}"
        imagePullPolicy: {{ .Values.tunnel.image.pullPolicy | default "IfNotPresent" }}
        env:
        - name: FRP_STCP_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-secrets"
              key: "stcp-key"
        command: ["/usr/local/bin/entrypoint.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/frp/frpc.toml
          subPath: frpc.toml
        - name: token-volume
          mountPath: /etc/frp/token
          subPath: frp-token
        - name: entrypoint-volume
          mountPath: /usr/local/bin/entrypoint.sh
          subPath: entrypoint.sh
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: "{{ .Release.Name }}-frpc-config"
      - name: token-volume
        secret:
          secretName: "{{ .Release.Name }}-secrets"
          items:
          - key: frp-client-token
            path: frp-token
      - name: entrypoint-volume
        configMap:
          name: {{ .Release.Name }}-frpc-entrypoint-config
          defaultMode: 0755
